---
- name: Display distribution
  ansible.builtin.debug:
    msg: "{{ ansible_distribution }}"

- name: Display distribution release
  ansible.builtin.debug:
    msg: "{{ ansible_distribution_release }}"

- name: Display distribution version
  ansible.builtin.debug:
    msg: "{{ ansible_distribution_version }}"

- name: Display OS family
  ansible.builtin.debug:
    msg: "{{ ansible_os_family }}"

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
